yy-choose
Blackfeather007/tactics-in-lean pull request #5
Opened 2024-12-20 06:04 UTC by yuanyi-350

2024-12-20 09:03 UTC, yuanyi-350 commented
I suggest placing this section after the Teaching Structure section. P.S. The structure will help in understanding type transformation

2024-12-21 03:42 UTC, timechess commented
Put your exercises in another file like `choose.lean`

2024-12-21 05:51 UTC, yuanyi-350 commented
Ok, I have already revised it.

2024-12-24 13:47 UTC, timechess requested changes

2024-12-24 13:47 UTC, timechess commented on TacticsInLean/Choose.lean
> +section Introduction1
I think there should be a more gentle example(even without sorry just to show the usage) before this section

2024-12-24 13:47 UTC, timechess commented on TacticsInLean/Choose.lean
> +  have hg : ∀ (ε : ℝ) (a : ε > 0), P (g ε a) ε := sorry
I don't think do it separately will be a good idea. The example provided in `#help tactic` doesn't show how to do this.  You should provide an example or change it.

2024-12-24 13:47 UTC, timechess commented on TacticsInLean/Choose.lean
> +  have hf : ∀ x ∈ Prod.fst '' s, (x, f x) ∈ s := sorry
Same as above

2024-12-24 13:47 UTC, timechess commented on TacticsInLean/Choose.lean
> +def Hom_top_product_of_normal_of_disjoint (H K : Set ℝ) : (H * K) → (H × K) := by
You should provide natural language description about this definition.

2024-12-25 03:58 UTC, timechess approved these changes

2024-12-25 04:00 UTC, merged